### ISSUE TITLE
Bug: Error while deploying the chat-chainlit-app

### ISSUE THREAD

**Issue by sreedharguda** [awslabs/multi-agent-orchestrator#167]
### Expected Behaviour

While running the chat-chainlit-app getting the below error message. I am using the python version 3.12.6 and chainlit 1.3.2 

>python app.py
Traceback (most recent call last):
  File "C:xxxxxxxxxxxxxxxxxxxx\multi-agent-orchestrator\examples\chat-chainlit-app\app.py", line 2, in <module>
    import chainlit as cl
  File "C:xxxxxxxxxxxxxxxxxxxx\multi-agent-orchestrator\examples\chat-chainlit-app\venv\Lib\site-packages\chainlit\__init__.py", line 18, in <module>
    from chainlit.action import Action
  File "C:xxxxxxxxxxxxxxxxxxxx\multi-agent-orchestrator\examples\chat-chainlit-app\venv\Lib\site-packages\chainlit\action.py", line 5, in <module>
    from chainlit.telemetry import trace_event
  File "C:xxxxxxxxxxxxxxxxxxxx\multi-agent-orchestrator\examples\chat-chainlit-app\venv\Lib\site-packages\chainlit\telemetry.py", line 12, in <module>
    from chainlit.config import config
  File "C:xxxxxxxxxxxxxxxxxxxx\multi-agent-orchestrator\examples\chat-chainlit-app\venv\Lib\site-packages\chainlit\config.py", line 538, in <module>
    config = load_config()
             ^^^^^^^^^^^^^
  File "C:xxxxxxxxxxxxxxxxxxxx\multi-agent-orchestrator\examples\chat-chainlit-app\venv\Lib\site-packages\chainlit\config.py", line 507, in load_config
    settings = load_settings()
               ^^^^^^^^^^^^^^^
  File "C:xxxxxxxxxxxxxxxxxxxx\multi-agent-orchestrator\examples\chat-chainlit-app\venv\Lib\site-packages\chainlit\config.py", line 479, in load_settings
    code_settings = CodeSettings(action_callbacks={})
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:xxxxxxxxxxxxxxxxxxxx\multi-agent-orchestrator\examples\chat-chainlit-app\venv\Lib\site-packages\pydantic\_internal\_dataclasses.py", line 121, in __init__
    s.__pydantic_validator__.validate_python(ArgsKwargs(args, kwargs), self_instance=s)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:xxxxxxxxxxxxxxxxxxxx\multi-agent-orchestrator\examples\chat-chainlit-app\venv\Lib\site-packages\pydantic\_internal\_mock_val_ser.py", line 100, in __getattr__
    raise PydanticUserError(self._error_message, code=self._code)
pydantic.errors.PydanticUserError: `CodeSettings` is not fully defined; you should define `Action`, then call `pydantic.dataclasses.rebuild_dataclass(CodeSettings)`.

### Current Behaviour

Getting the error.

### Code snippet

```python
Used the code from this repo https://github.com/awslabs/multi-agent-orchestrator/tree/main/examples/chat-chainlit-app and followed the steps as well.
```

### Steps to Reproduce

https://github.com/awslabs/multi-agent-orchestrator/tree/main/examples/chat-chainlit-app

**Comment by brnaba-aws** [comment]
Hi @sreedharguda ,
Thanks for using the multi-agent orchestrator. It seems like this issue is related to pydantic version not aligned with chainlit.

We have updated our requirements.txt which should fix the issue and let you use the chainlit app.
Let us know how it goes and if we can close the issue.
Anthony

**Comment by sreedharguda** [comment]
Hi @brnaba-aws , Thank you for your help, now am able to run the code and its working as expected. Please close the issue.

**Comment by sreedharguda** [comment]
Hi @brnaba-aws , Thank you for your help, now am able to run the code and its working as expected. Please close the issue.
