### ISSUE TITLE
Bug: Quickstart.py error: you must specify a region

### ISSUE THREAD

**Issue by ab94amz** [awslabs/multi-agent-orchestrator#38]
### Expected Behaviour

Running Quickstart.py example https://awslabs.github.io/multi-agent-orchestrator/general/quickstart/

### Current Behaviour

Traceback (most recent call last):
  File "/Volumes/workplace/Test/Agents/multi-agent-orchestrator/quickstart.py", line 6, in <module>
    from multi_agent_orchestrator.orchestrator import MultiAgentOrchestrator, OrchestratorConfig
  File "/Volumes/workplace/Test/Agents/multi-agent-orchestrator/env/lib/python3.12/site-packages/multi_agent_orchestrator/orchestrator.py", line 20, in <module>
    class MultiAgentOrchestrator:
  File "/Volumes/workplace/Test/Agents/multi-agent-orchestrator/env/lib/python3.12/site-packages/multi_agent_orchestrator/orchestrator.py", line 24, in MultiAgentOrchestrator
    classifer: Classifier = BedrockClassifier(options=BedrockClassifierOptions()),
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/workplace/Test/Agents/multi-agent-orchestrator/env/lib/python3.12/site-packages/multi_agent_orchestrator/classifiers/bedrock_classifier.py", line 25, in __init__
    super().__init__()
  File "/Volumes/workplace/Test/Agents/multi-agent-orchestrator/env/lib/python3.12/site-packages/multi_agent_orchestrator/classifiers/classifier.py", line 16, in __init__
    self.default_agent = BedrockLLMAgent(
                         ^^^^^^^^^^^^^^^^
  File "/Volumes/workplace/Test/Agents/multi-agent-orchestrator/env/lib/python3.12/site-packages/multi_agent_orchestrator/agents/bedrock_llm_agent.py", line 30, in __init__
    self.client = boto3.client('bedrock-runtime')
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/workplace/Test/Agents/multi-agent-orchestrator/env/lib/python3.12/site-packages/boto3/__init__.py", line 92, in client
    return _get_default_session().client(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/workplace/Test/Agents/multi-agent-orchestrator/env/lib/python3.12/site-packages/boto3/session.py", line 297, in client
    return self._session.create_client(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/workplace/Test/Agents/multi-agent-orchestrator/env/lib/python3.12/site-packages/botocore/session.py", line 997, in create_client
    client = client_creator.create_client(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/workplace/Test/Agents/multi-agent-orchestrator/env/lib/python3.12/site-packages/botocore/client.py", line 161, in create_client
    client_args = self._get_client_args(
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/workplace/Test/Agents/multi-agent-orchestrator/env/lib/python3.12/site-packages/botocore/client.py", line 520, in _get_client_args
    return args_creator.get_client_args(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/workplace/Test/Agents/multi-agent-orchestrator/env/lib/python3.12/site-packages/botocore/args.py", line 101, in get_client_args
    final_args = self.compute_client_args(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/workplace/Test/Agents/multi-agent-orchestrator/env/lib/python3.12/site-packages/botocore/args.py", line 220, in compute_client_args
    endpoint_config = self._compute_endpoint_config(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/workplace/Test/Agents/multi-agent-orchestrator/env/lib/python3.12/site-packages/botocore/args.py", line 370, in _compute_endpoint_config
    return self._resolve_endpoint(**resolve_endpoint_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/workplace/Test/Agents/multi-agent-orchestrator/env/lib/python3.12/site-packages/botocore/args.py", line 475, in _resolve_endpoint
    return endpoint_bridge.resolve(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/workplace/Test/Agents/multi-agent-orchestrator/env/lib/python3.12/site-packages/botocore/client.py", line 625, in resolve
    resolved = self.endpoint_resolver.construct_endpoint(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/workplace/Test/Agents/multi-agent-orchestrator/env/lib/python3.12/site-packages/botocore/regions.py", line 230, in construct_endpoint
    result = self._endpoint_for_partition(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/workplace/Test/Agents/multi-agent-orchestrator/env/lib/python3.12/site-packages/botocore/regions.py", line 278, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.

### Code snippet

```python
https://awslabs.github.io/multi-agent-orchestrator/general/quickstart/
```

### Steps to Reproduce

https://awslabs.github.io/multi-agent-orchestrator/general/quickstart/

**Comment by ab94amz** [comment]
solved with export AWS_DEFAULT_REGION=us-east-1

**Comment by brnaba-aws** [comment]
Thanks for picking this up, we will update the documentation with that line.
